//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_STD_Boletin
    {
        public int CodigoBoletin { get; set; }
        public Nullable<int> CodigoTipoBoletin { get; set; }
        public string NombreDocumento { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Descripcion { get; set; }
        public string NombreArchivo { get; set; }
    }
}
