//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_STD_Municipio
    {
        public int Municipio_ID { get; set; }
        public Nullable<int> Departamento_ID { get; set; }
        public string Municipio_DSC { get; set; }
    }
}
