//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DYR_Movil
    {
        public System.Guid Codigo { get; set; }
        public int Cuenca_ID { get; set; }
        public int SubCuencaRio_ID { get; set; }
        public int PuntoMonitoreo_ID { get; set; }
        public int ModeloMolinete_ID { get; set; }
        public int TipoMedicion_ID { get; set; }
        public int Tipologia_ID { get; set; }
        public Nullable<System.DateTime> FechaHoraInicial { get; set; }
        public Nullable<System.DateTime> FechaHoraFinal { get; set; }
        public decimal GpsLatitud { get; set; }
        public decimal GpsLongitud { get; set; }
        public byte[] FotografiaNorte { get; set; }
        public byte[] FotografiaSur { get; set; }
        public string Comentario { get; set; }
        public int Estado_ID { get; set; }
        public string Usuario { get; set; }
        public Nullable<decimal> Caudal { get; set; }
    }
}
