//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DYR_Plantilla_Encabezado
    {
        public int DYR_ID { get; set; }
        public string DYR_DSC { get; set; }
        public int Organizacion_ID { get; set; }
    }
}
