//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DYR_Movil_Detalle
    {
        public System.Guid Codigo { get; set; }
        public int NoCorrelativo { get; set; }
        public Nullable<decimal> MedicionBaseInicial { get; set; }
        public Nullable<decimal> MedicionBaseFinal { get; set; }
        public Nullable<decimal> SectorMetros { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> Revoluciones { get; set; }
        public Nullable<decimal> Velocidad { get; set; }
        public Nullable<decimal> Caudal { get; set; }
    }
}
