//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DYR_Plantilla_Detalle_Cuenca
    {
        public int DYR_ID { get; set; }
        public int Cuenca_ID { get; set; }
        public int SubCuentaRio_ID { get; set; }
    }
}
