//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX_DYR_Movil_YoReporto
    {
        public System.Guid Codigo { get; set; }
        public Nullable<System.DateTime> FechaHoraInicial { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> TipoReporte_ID { get; set; }
        public Nullable<int> Departamento_ID { get; set; }
        public Nullable<int> Municipio_ID { get; set; }
        public string Barrio { get; set; }
        public string Direccion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<decimal> GpsLatitud { get; set; }
        public Nullable<decimal> GpsLongitud { get; set; }
        public byte[] Imagen { get; set; }
        public string Usuario { get; set; }
        public string Emei { get; set; }
    }
}
