//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Plantilla_Movil
    {
        public string Tabla { get; set; }
        public string Prefijo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> Orden { get; set; }
    }
}
